// <auto-generated />
// This file is included in the package for reference; the actual attribute is
// generated at build time via the .targets file.

using System;

namespace TestTrackingDiagrams.Tracking
{
    /// <summary>
    /// Activates IL-based assertion tracking for this assembly.
    /// When present, the TestTrackingDiagrams.AssertionTracking MSBuild task will
    /// instrument FluentAssertions <c>.Should()</c> call sites after compilation,
    /// wrapping each assertion statement in a try/catch that reports pass/fail
    /// to <c>Track.AssertionPassed</c>/<c>Track.AssertionFailed</c>.
    /// <para>
    /// Unlike the source-rewriting approach (<c>TrackAssertionsAttribute</c>),
    /// this preserves full C# semantics — null propagation, ref parameters, and
    /// expression evaluation order are unchanged.
    /// </para>
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly)]
    internal sealed class TrackAssertionsBetaAttribute : Attribute { }
}
