// <auto-generated />
// This file is delivered via NuGet contentFiles and compiled into your project.
// It is used to suppress automatic assertion rewriting on specific methods or classes.

using System;

namespace TestTrackingDiagrams.Tracking
{
    /// <summary>
    /// Suppresses automatic assertion rewriting for the decorated method or class.
    /// When applied, <c>.Should()</c> expression statements within the scope will
    /// not be wrapped in <c>Track.That(() =&gt; ...)</c> by the rewriter.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Class, Inherited = true)]
    internal sealed class SuppressAssertionTrackingAttribute : Attribute { }
}
