// <auto-generated />
// This file is delivered via NuGet contentFiles and compiled into your project.
// It is used to activate automatic assertion rewriting at compile time.

using System;

namespace TestTrackingDiagrams.Tracking
{
    /// <summary>
    /// Activates automatic assertion rewriting for this assembly.
    /// When present, the TestTrackingDiagrams.AssertionRewriter MSBuild task will
    /// wrap FluentAssertions <c>.Should()</c> expression statements in
    /// <c>Track.That(() =&gt; ...)</c> at compile time.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly)]
    internal sealed class TrackAssertionsAttribute : Attribute { }
}
